@startuml
package "Sistema de Aluguel de Automóveis" {

 
  package "Subsistema de Gestão de Pedidos e Contratos" {
    [Gestor de Pedidos] 
    [Gestor de Contratos]
    [Avaliação Financeira] 
    [Registro de Contratos]
    [Banco de Dados]
    [Backend (Java MVC)]
  }

  package "Subsistema de Construção Dinâmica de Páginas Web" {
    [Frontend (HTML)]
    [Serviços de API Rest]
    [Banco de Dados]
  }

  [Clientes] --> [Frontend (HTML)]
  [Agentes (Empresas e Bancos)] --> [Frontend (HTML)]
 
  [Backend (Java MVC)] --> [Serviços de API Rest]
  [Serviços de API Rest] --> [Banco de Dados]
  [Gestor de Pedidos] --> [Registro de Contratos]
  [Gestor de Pedidos] --> [Avaliação Financeira]
  [Avaliação Financeira] --> [Agentes (Empresas e Bancos)]
}
@enduml
